In [ ]:
# Mac OS버전
# %pip install torch torchvision
# Windows 버전
# %pip install torch torchvision --index-url https://download.pytorch.org/whl/cu126

Looking in indexes: https://download.pytorch.org/whl/cu126
     ---------------------------------------- 0.0/536.2 kB ? eta -:--:--
     ---------------------------------------- 536.2/536.2 kB 5.8 MB/s  0:00:00
   ---------------------------------------- 0.0/2.6 GB ? eta -:--:--
   ---------------------------------------- 0.0/2.6 GB 60.7 MB/s eta 0:00:43
   ---------------------------------------- 0.0/2.6 GB 60.5 MB/s eta 0:00:43
    --------------------------------------- 0.0/2.6 GB 60.0 MB/s eta 0:00:43
    --------------------------------------- 0.1/2.6 GB 60.2 MB/s eta 0:00:43
    --------------------------------------- 0.1/2.6 GB 59.2 MB/s eta 0:00:43
   - -------------------------------------- 0.1/2.6 GB 59.8 MB/s eta 0:00:42
   - -------------------------------------- 0.1/2.6 GB 59.4 MB/s eta 0:00:42
   - -------------------------------------- 0.1/2.6 GB 59.6 MB/s eta 0:00:42
   - -------------------------------------- 0.1/2.6 GB 59.6 MB/s eta 0:00:42
   - ----------------------

In [5]:
import torch

In [6]:
# GPU 사용 할 수 있는 여부
torch.cuda.is_available()

False

In [7]:
torch.__version__

'2.9.0'

In [8]:
import numpy as np

In [9]:
data = [[1, 2],
        [3, 4]]

In [10]:
x = torch.tensor(data)
x

tensor([[1, 2],
        [3, 4]])

In [ ]:
# 넘파이 경우 텐서파일로 만든 방법
x_np = np.array(x)

x_tensor = torch.from_numpy(x_np)
x_tensor

/var/folders/s3/2n7b_c090wn9dg5gvs55lrtr0000gn/T/ipykernel_95028/2376230143.py:1: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  x_np = np.array(x)


tensor([[1, 2],
        [3, 4]])

In [15]:
x[0]

tensor([1, 2])

In [16]:
x[0][0]

tensor(1)

In [ ]:
# shape
x.size()

torch.Size([2, 2])

In [ ]:
# 터치 객체
x[0].size()

torch.Size([2])

In [ ]:
# 그냥 값
x.size(0)

2

In [20]:
y = torch.tensor(np.array([[5, 6],[7, 8]]))


In [ ]:
x + y

tensor([[ 6,  8],
        [10, 12]])

In [22]:
torch.add(x, y)

tensor([[ 6,  8],
        [10, 12]])

In [23]:
x.add(y)

tensor([[ 6,  8],
        [10, 12]])

In [24]:
y

tensor([[5, 6],
        [7, 8]])

In [25]:
# inplace=True , 원본에다가 수정한 값을 그대로 넣는것, 판다스 데이터 프레임에서 inplace 사용됨 
y.add_(x)

tensor([[ 6,  8],
        [10, 12]])

In [26]:
y

tensor([[ 6,  8],
        [10, 12]])

In [ ]:
# view : reshape 해줌
x_reshape01 = x.view(4)
x_reshape01

tensor([1, 2, 3, 4])

In [28]:
x_reshape02 = x.view(-1)
x_reshape02

tensor([1, 2, 3, 4])

In [29]:
x_to_np = x.numpy()
x_to_np

array([[1, 2],
       [3, 4]])

In [30]:
type(x_to_np)

numpy.ndarray

In [ ]:
# 텐서 객체를 넘파이로 바꾼다.
type(x)

torch.Tensor