In [1]:
from random import random

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
import numpy as np
import pandas as pd

In [9]:
random_num = np.random.randint(1, 101, [3, 3])
random_num
print(random_num)

array([[49, 69, 31],
       [21,  2, 79],
       [45, 41,  9]])

[[49 69 31]
 [21  2 79]
 [45 41  9]]


In [10]:
df_num = pd.DataFrame(random_num)
df_num
print(df_num)

0   1   2
0  49  69  31
1  21   2  79
2  45  41   9

    0   1   2
0  49  69  31
1  21   2  79
2  45  41   9


In [5]:
df_num = pd.DataFrame(random_num, index=['row1', 'row2', 'row3'])
df_num

0   1   2
row1  84  47  52
row2  97  89  72
row3  33  74   7

In [8]:
df_num = pd.DataFrame(data=random_num,
                      index=['row1', 'row2', 'row3'],
                      columns=['col1', 'col2', 'col3'])
df_num

col1  col2  col3
row1    84    47    52
row2    97    89    72
row3    33    74     7

In [11]:
books = {
    "title" : ["개미", "고구려", "드래곤라자", "퇴마록"],
    "writer" : ["베르나르 베르베르", " 김진명", "이영도", "이우혁"],
    "publisher" : ["열린책들", "이타북스", "황금가지", "들녘"],
    "1st-edition" : ["2013-05-30", "2011-02-28", "1998-05-30", "1994-01-01"],
    "price" : [15000, 15000, 6300, 8550]
}
books

{'title': ['개미', '고구려', '드래곤라자', '퇴마록'],
 'writer': ['베르나르 베르베르', ' 김진명', '이영도', '이우혁'],
 'publisher': ['열린책들', '이타북스', '황금가지', '들녘'],
 '1st-edition': ['2013-05-30', '2011-02-28', '1998-05-30', '1994-01-01'],
 'price': [15000, 15000, 6300, 8550]}

In [13]:
df_books = pd.DataFrame(books)
df_books

title     writer publisher 1st-edition  price
0     개미  베르나르 베르베르      열린책들  2013-05-30  15000
1    고구려        김진명      이타북스  2011-02-28  15000
2  드래곤라자        이영도      황금가지  1998-05-30   6300
3    퇴마록        이우혁        들녘  1994-01-01   8550

In [18]:
df_books.index
df_books.columns
df_books.shape
df_books.size
print(df_books.dtypes)
type(df_books.dtypes)
print(df_books.count())

RangeIndex(start=0, stop=4, step=1)

Index(['title', 'writer', 'publisher', '1st-edition', 'price'], dtype='object')

(4, 5)

20

title          object
writer         object
publisher      object
1st-edition    object
price           int64
dtype: object


pandas.core.series.Series

title          4
writer         4
publisher      4
1st-edition    4
price          4
dtype: int64


In [19]:
df_books.info
df_books.info()

<bound method DataFrame.info of    title     writer publisher 1st-edition  price
0     개미  베르나르 베르베르      열린책들  2013-05-30  15000
1    고구려        김진명      이타북스  2011-02-28  15000
2  드래곤라자        이영도      황금가지  1998-05-30   6300
3    퇴마록        이우혁        들녘  1994-01-01   8550>

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   title        4 non-null      object
 1   writer       4 non-null      object
 2   publisher    4 non-null      object
 3   1st-edition  4 non-null      object
 4   price        4 non-null      int64 
dtypes: int64(1), object(4)
memory usage: 292.0+ bytes


In [20]:
df_books['title'][0]

'개미'

In [21]:
type(df_books['title'])

pandas.core.series.Series

In [23]:
df_books['price'].max()
# series 의 max 이다

np.int64(15000)

In [24]:
df_books.sort_values(by="price")

title     writer publisher 1st-edition  price
2  드래곤라자        이영도      황금가지  1998-05-30   6300
3    퇴마록        이우혁        들녘  1994-01-01   8550
0     개미  베르나르 베르베르      열린책들  2013-05-30  15000
1    고구려        김진명      이타북스  2011-02-28  15000

In [28]:
df_books.sort_values(["price"], ascending=False)
# ascending=False 높은 차순부터 정렬해주세요

title     writer publisher 1st-edition  price
0     개미  베르나르 베르베르      열린책들  2013-05-30  15000
1    고구려        김진명      이타북스  2011-02-28  15000
3    퇴마록        이우혁        들녘  1994-01-01   8550
2  드래곤라자        이영도      황금가지  1998-05-30   6300

In [26]:
df_books.sort_values(["price","1st-edition"], ascending=False)

title     writer publisher 1st-edition  price
0     개미  베르나르 베르베르      열린책들  2013-05-30  15000
1    고구려        김진명      이타북스  2011-02-28  15000
3    퇴마록        이우혁        들녘  1994-01-01   8550
2  드래곤라자        이영도      황금가지  1998-05-30   6300

In [27]:
df_books.sort_values(["price","1st-edition"], ascending=[False,True])

title     writer publisher 1st-edition  price
1    고구려        김진명      이타북스  2011-02-28  15000
0     개미  베르나르 베르베르      열린책들  2013-05-30  15000
3    퇴마록        이우혁        들녘  1994-01-01   8550
2  드래곤라자        이영도      황금가지  1998-05-30   6300

In [29]:
df_books.sort_index()

title     writer publisher 1st-edition  price
0     개미  베르나르 베르베르      열린책들  2013-05-30  15000
1    고구려        김진명      이타북스  2011-02-28  15000
2  드래곤라자        이영도      황금가지  1998-05-30   6300
3    퇴마록        이우혁        들녘  1994-01-01   8550

In [30]:
df_books.sort_index(axis=1)

1st-edition  price publisher  title     writer
0  2013-05-30  15000      열린책들     개미  베르나르 베르베르
1  2011-02-28  15000      이타북스    고구려        김진명
2  1998-05-30   6300      황금가지  드래곤라자        이영도
3  1994-01-01   8550        들녘    퇴마록        이우혁

In [31]:
df_books.sort_index(axis="columns")

1st-edition  price publisher  title     writer
0  2013-05-30  15000      열린책들     개미  베르나르 베르베르
1  2011-02-28  15000      이타북스    고구려        김진명
2  1998-05-30   6300      황금가지  드래곤라자        이영도
3  1994-01-01   8550        들녘    퇴마록        이우혁

In [32]:
df_title = df_books.set_index("title")
df_title

writer publisher 1st-edition  price
title                                        
개미     베르나르 베르베르      열린책들  2013-05-30  15000
고구려          김진명      이타북스  2011-02-28  15000
드래곤라자        이영도      황금가지  1998-05-30   6300
퇴마록          이우혁        들녘  1994-01-01   8550

In [33]:
df_title.index

Index(['개미', '고구려', '드래곤라자', '퇴마록'], dtype='object', name='title')

In [34]:
df_title.values

array([['베르나르 베르베르', '열린책들', '2013-05-30', 15000],
       [' 김진명', '이타북스', '2011-02-28', 15000],
       ['이영도', '황금가지', '1998-05-30', 6300],
       ['이우혁', '들녘', '1994-01-01', 8550]], dtype=object)

In [35]:
df_title.sort_index(ascending=False)

writer publisher 1st-edition  price
title                                        
퇴마록          이우혁        들녘  1994-01-01   8550
드래곤라자        이영도      황금가지  1998-05-30   6300
고구려          김진명      이타북스  2011-02-28  15000
개미     베르나르 베르베르      열린책들  2013-05-30  15000

In [36]:
# type(df_books.sort_index())
df_title["price"]

title
개미       15000
고구려      15000
드래곤라자     6300
퇴마록       8550
Name: price, dtype: int64

In [37]:
df_title.nlargest(3, columns="price")

writer publisher 1st-edition  price
title                                        
개미     베르나르 베르베르      열린책들  2013-05-30  15000
고구려          김진명      이타북스  2011-02-28  15000
퇴마록          이우혁        들녘  1994-01-01   8550

In [38]:
df_title.nsmallest(2, columns="price")

writer publisher 1st-edition  price
title                                    
드래곤라자    이영도      황금가지  1998-05-30   6300
퇴마록      이우혁        들녘  1994-01-01   8550

In [39]:
df_title.sum()
# 컬럼별로 더하더라

writer                              베르나르 베르베르 김진명이영도이우혁
publisher                                열린책들이타북스황금가지들녘
1st-edition    2013-05-302011-02-281998-05-301994-01-01
price                                             44850
dtype: object

In [40]:
df_title["price"].sum()

np.int64(44850)

In [41]:
df_title.sum(numeric_only=True)

price    44850
dtype: int64

In [42]:
print(df_title.mean(numeric_only=True))
print(df_title.median(numeric_only=True))
print(df_title.std(numeric_only=True))

price    11212.5
dtype: float64
price    11775.0
dtype: float64
price    4468.850523
dtype: float64


In [43]:
df_title.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, 개미 to 퇴마록
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   writer       4 non-null      object
 1   publisher    4 non-null      object
 2   1st-edition  4 non-null      object
 3   price        4 non-null      int64 
dtypes: int64(1), object(3)
memory usage: 332.0+ bytes


In [44]:
df_title.info

<bound method DataFrame.info of           writer publisher 1st-edition  price
title                                        
개미     베르나르 베르베르      열린책들  2013-05-30  15000
고구려          김진명      이타북스  2011-02-28  15000
드래곤라자        이영도      황금가지  1998-05-30   6300
퇴마록          이우혁        들녘  1994-01-01   8550>

In [45]:
df_title.select_dtypes("object")
# object 만 보여줘

writer publisher 1st-edition
title                                 
개미     베르나르 베르베르      열린책들  2013-05-30
고구려          김진명      이타북스  2011-02-28
드래곤라자        이영도      황금가지  1998-05-30
퇴마록          이우혁        들녘  1994-01-01

In [46]:
df_title["1st-edition"] = pd.to_datetime(df_title["1st-edition"])

In [47]:
df_title.select_dtypes("object")
# 날짜 타입으로 바껴서 오브젝트에서 빠진다

writer publisher
title                     
개미     베르나르 베르베르      열린책들
고구려          김진명      이타북스
드래곤라자        이영도      황금가지
퇴마록          이우혁        들녘

In [48]:
df_title.select_dtypes(include="object")

writer publisher
title                     
개미     베르나르 베르베르      열린책들
고구려          김진명      이타북스
드래곤라자        이영도      황금가지
퇴마록          이우혁        들녘

In [49]:
df_title.select_dtypes(exclude="object")

1st-edition  price
title                   
개미     2013-05-30  15000
고구려    2011-02-28  15000
드래곤라자  1998-05-30   6300
퇴마록    1994-01-01   8550

In [50]:
df_title["price"]

title
개미       15000
고구려      15000
드래곤라자     6300
퇴마록       8550
Name: price, dtype: int64

In [51]:
df_title["publisher"]

title
개미       열린책들
고구려      이타북스
드래곤라자    황금가지
퇴마록        들녘
Name: publisher, dtype: object

In [53]:
df_title[["price","publisher"]]
# 두 항목을 같이 보고 싶을 때 []를 한번 더 감싸서 출력해야 한다.

price publisher
title                 
개미     15000      열린책들
고구려    15000      이타북스
드래곤라자   6300      황금가지
퇴마록     8550        들녘

In [57]:
# location에 있는 인덱스 하나를 가지고 오는 것 loc
print(df_title.loc["드래곤라자"])


writer                         이영도
publisher                     황금가지
1st-edition    1998-05-30 00:00:00
price                         6300
Name: 드래곤라자, dtype: object


In [60]:
# 인티저 locatoion
print(df_title.iloc[2])

writer                         이영도
publisher                     황금가지
1st-edition    1998-05-30 00:00:00
price                         6300
Name: 드래곤라자, dtype: object


In [63]:
df_title.loc[["고구려","드래곤라자"]]

writer publisher 1st-edition  price
title                                    
고구려      김진명      이타북스  2011-02-28  15000
드래곤라자    이영도      황금가지  1998-05-30   6300

In [65]:
df_title.iloc[2:4]

writer publisher 1st-edition  price
title                                    
드래곤라자    이영도      황금가지  1998-05-30   6300
퇴마록      이우혁        들녘  1994-01-01   8550