# MarkDown

**명령어**

enter : edit mode

esc : command mode

[edit mode] ctrl + enter : 실행

[edit mode] shift + enter :  실행 및 다음 cell 선택

[edit mode] alt + enter : 실행 및 새로운 cell 생성

[command mode] + a : 현재 cell 위에 cell 추가

[command mode] + b : 현재 cell  아래에 cell 추가

[command mode] + y : 현재 cell을 code cell로 변경

[command mode] + m : 현재 cell을 markdown cell로 변경

! : shell 명령어 사용

%  : magic function  사용 (!와 거의 동일하지만, python 명령어이다!!!)

In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
np.__version__

'2.2.6'

In [4]:
print(np.__version__)

2.2.6


In [5]:
# 자동완성 : tab
# docstring (설명) : shift + tab
np.array

<function numpy.array>

In [6]:
arr01 = np.array([1, 2, 3, 4, 5])
arr01

array([1, 2, 3, 4, 5])

In [8]:
type(arr01)
# ndarray : n dimensional array (n차원 배열)

numpy.ndarray

In [10]:
arr02 = np.array([
    [1.1, 2.2, 3.3],
    [4, 5, 6,]
])
arr02

array([[1.1, 2.2, 3.3],
       [4. , 5. , 6. ]])

In [11]:
list_dim3 = [
    [["1"],["2"],["3"]],
    [[4],[5],[6]],
    [[7],[8],[9]],
    [["10"],["11"],["12"]]
]
arr03 = np.array(list_dim3)
arr03

array([[['1'],
        ['2'],
        ['3']],

       [['4'],
        ['5'],
        ['6']],

       [['7'],
        ['8'],
        ['9']],

       [['10'],
        ['11'],
        ['12']]], dtype='<U21')

In [12]:
# shape :  차원 출력 (1, 2, 3, ... n차원)

# (5, ) 1차원 데이터 5개
print(arr01.shape)
# (2, 3) 2차원 , 2행 3열
print(arr02.shape)
# (4, 3, 1) 3차원, 4개의 2차원 -> (3, 1) : 3행 1열
print(arr03.shape)

(5,)
(2, 3)
(4, 3, 1)


In [13]:
# ndim : 차원의 갯수
print(arr01.ndim)
print(arr02.ndim)
print(arr03.ndim)

1
2
3


In [14]:
# dtyoe : ndarray 내부의 값들이 어떤 type인지. 64 비트
print(arr01.dtype)
print(arr02.dtype)
print(arr03.dtype)

int64
float64
<U21


In [15]:
# size : 행 * 열
print(arr01.size)
print(arr02.size)
print(arr03.size)

5
6
12


In [16]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# print 없이 여러 개의 변수를 모두 출력!

In [17]:
arr01.size
arr02.size
arr03.size

5

6

12

In [18]:
np.arange(3)

array([0, 1, 2])

In [19]:
np.arange(1, 5)

array([1, 2, 3, 4])

In [21]:
arr04 = np.arange(0, 11, 2)
arr04
arr04.shape # 몇 차원 몇 열

array([ 0,  2,  4,  6,  8, 10])

(6,)

In [24]:
arr04 = arr04.reshape(2, 3)
arr04.shape
arr04

(2, 3)

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [25]:
arr05 = np.arange(100)
arr05

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [26]:
arr05.reshape(2,3)
# ValueError: cannot reshape array of size 100 into shape (2,3)

ValueError: cannot reshape array of size 100 into shape (2,3)

In [28]:
# -1 : numpy가 알아서 추론
arr05 = arr05.reshape(2, -1)
arr05

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98, 99]])

In [31]:
arr05 = arr05.reshape(-1, 2)
arr05.shape
arr05

(50, 2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39],
       [40, 41],
       [42, 43],
       [44, 45],
       [46, 47],
       [48, 49],
       [50, 51],
       [52, 53],
       [54, 55],
       [56, 57],
       [58, 59],
       [60, 61],
       [62, 63],
       [64, 65],
       [66, 67],
       [68, 69],
       [70, 71],
       [72, 73],
       [74, 75],
       [76, 77],
       [78, 79],
       [80, 81],
       [82, 83],
       [84, 85],
       [86, 87],
       [88, 89],
       [90, 91],
       [92, 93],
       [94, 95],
       [96, 97],
       [98, 99]])

In [32]:
arr05 = arr05.reshape(2, -1, 5)
arr05.shape
arr05

(2, 10, 5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [41]:
arr06 = np.zeros(5)
arr07 = np.ones(10)
arr08 = np.empty(5)

In [43]:
arr06
arr07
arr08

array([0., 0., 0., 0., 0.])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

array([ 1.  ,  2.75,  6.  , 10.75, 17.  ])

In [45]:
np.linspace(0, 10, num=5)
np.linspace(0, 12, num=5)
np.linspace(0, 12, num=3)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

array([ 0.,  3.,  6.,  9., 12.])

array([ 0.,  6., 12.])

In [50]:
np.full((2, 3), 4)

array([[4, 4, 4],
       [4, 4, 4]])

In [51]:
# 단위행렬 :  곱셈에 대한 항등원 : 행렬을 곱하기 해서 자기 자신이 나오는 값
# 3행에 대한 단위행렬
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [54]:
np.random.random() # 0<= n <1 의 난수를 만든다.
np.random.random(5)
np.random.random((2, 3))

0.44423676794805567

array([0.09118973, 0.05487309, 0.02159387, 0.78083452, 0.19445733])

array([[0.67012183, 0.96829124, 0.6324519 ],
       [0.05298201, 0.83500149, 0.86335344]])

In [55]:
list(np.random.random(5))

[np.float64(0.5614038527795673),
 np.float64(0.1776334200639439),
 np.float64(0.5291753115218769),
 np.float64(0.43904795726632295),
 np.float64(0.12829606739857746)]

In [62]:
np.random.seed(1) # random을 고정해준다. 싱글론 2**32-1 이내의 random와 계산식을 통해 특정 값을 전달해준다.
np.random.randint(0, 10, (2, 3))

array([[5, 8, 9],
       [5, 0, 0]])

In [63]:
# 표준 정규분포에 맞게 설정된 난수
np.random.randn(5)
np.random.randn(2, 3)

array([-1.601721  , -1.47782957,  0.48349585,  0.18843661, -0.46468632])

array([[ 0.86182712, -2.65426198,  1.15226492],
       [ 0.19664341, -1.54521415, -0.08810409]])

In [66]:
np.arange(1, 101)
np.arange(1, 101).dtype

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

dtype('int64')

In [67]:
np.arange(1, 101, dtype=float)

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])