In [2]:
import numpy as np

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
a = np.arange(1, 10).reshape(3, 3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
# scalar 연산
print(a + 1)
print(a - 2)
print(a * 3)
print(a / 4)
print(a % 5)


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]
[[0.25 0.5  0.75]
 [1.   1.25 1.5 ]
 [1.75 2.   2.25]]
[[1 2 3]
 [4 0 1]
 [2 3 4]]


In [7]:
from IPython.core.interactiveshell import  InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [8]:
a + 1
a - 2
a * 3
a / 4
a % 5

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

array([[0.25, 0.5 , 0.75],
       [1.  , 1.25, 1.5 ],
       [1.75, 2.  , 2.25]])

array([[1, 2, 3],
       [4, 0, 1],
       [2, 3, 4]])

In [9]:
a =  a + 1

In [10]:
a

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [11]:
a.sum()

np.int64(54)

In [12]:
# axis 0 :  "행 기준으로" 열 index sum
# axis 1 :  "열 기준으로" 행 index sum
a.sum(axis=0)
a.sum(axis=1)

array([15, 18, 21])

array([ 9, 18, 27])

In [16]:
a.max()
np.max(a)
np.max(a, axis=0)
np.max(a, axis=1)

np.int64(10)

np.int64(10)

array([ 8,  9, 10])

array([ 4,  7, 10])

In [15]:
a.min()
np.min(a)
np.min(a, axis=0)
np.min(a, axis=1)

np.int64(2)

np.int64(2)

array([2, 3, 4])

array([2, 5, 8])

In [18]:
# mean : 평균
a.mean()
np.mean(a)
np.mean(a,axis=0)
np.mean(a,axis=1)

np.float64(6.0)

np.float64(6.0)

array([5., 6., 7.])

array([3., 6., 9.])

In [19]:
# 중앙값 (중위값)
# a.median()
np.median(a)
np.median(a, axis=0)
np.median(a, axis=1)

np.float64(6.0)

array([5., 6., 7.])

array([3., 6., 9.])

In [21]:
# 표준편차
a.std()
np.std(a)
np.std(a, axis=0)
np.std(a, axis=1)

np.float64(2.581988897471611)

np.float64(2.581988897471611)

array([2.44948974, 2.44948974, 2.44948974])

array([0.81649658, 0.81649658, 0.81649658])

In [22]:
# 제곱근
np.sqrt(a)

array([[1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766]])

In [23]:
# 지수함수 (e^x)
# e : 자연상수, 오릴러 상수(euler's number)
np.exp(a)


array([[7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04]])

In [24]:
np.sin(a)
np.cos(a)
np.tan(a)

array([[ 0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111]])

array([[-0.41614684, -0.9899925 , -0.65364362],
       [ 0.28366219,  0.96017029,  0.75390225],
       [-0.14550003, -0.91113026, -0.83907153]])

array([[-2.18503986, -0.14254654,  1.15782128],
       [-3.38051501, -0.29100619,  0.87144798],
       [-6.79971146, -0.45231566,  0.64836083]])

In [25]:
b = np.arange(3, 30, 3).reshape(3, 3)
c = np.arange(20, 2, -2).reshape(3, 3)
b

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [26]:
c

array([[20, 18, 16],
       [14, 12, 10],
       [ 8,  6,  4]])

In [27]:
b + c

array([[23, 24, 25],
       [26, 27, 28],
       [29, 30, 31]])

In [28]:
b - c

array([[-17, -12,  -7],
       [ -2,   3,   8],
       [ 13,  18,  23]])

In [29]:
b * c

array([[ 60, 108, 144],
       [168, 180, 180],
       [168, 144, 108]])

In [30]:
b / c

array([[0.15      , 0.33333333, 0.5625    ],
       [0.85714286, 1.25      , 1.8       ],
       [2.625     , 4.        , 6.75      ]])

In [31]:
np.add(b, c)


array([[23, 24, 25],
       [26, 27, 28],
       [29, 30, 31]])

In [32]:
np.subtract(b, c)

array([[-17, -12,  -7],
       [ -2,   3,   8],
       [ 13,  18,  23]])

In [33]:
np.multiply(b, c)

array([[ 60, 108, 144],
       [168, 180, 180],
       [168, 144, 108]])

In [34]:
np.divide(b, c)

array([[0.15      , 0.33333333, 0.5625    ],
       [0.85714286, 1.25      , 1.8       ],
       [2.625     , 4.        , 6.75      ]])

In [35]:
# 나머지 연산
np.divmod(b, c)

(array([[0, 0, 0],
        [0, 1, 1],
        [2, 4, 6]]),
 array([[ 3,  6,  9],
        [12,  3,  8],
        [ 5,  0,  3]]))

In [36]:
# 내적
b @ c

array([[216, 180, 144],
       [594, 504, 414],
       [972, 828, 684]])

In [37]:
np.matmul(b, c)


array([[216, 180, 144],
       [594, 504, 414],
       [972, 828, 684]])

In [39]:
np.dot(b,c)

array([[216, 180, 144],
       [594, 504, 414],
       [972, 828, 684]])