In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"


In [2]:
import numpy as np

In [3]:
a = np.random.randint(1, 100, (3, 3))
a


array([[49, 92, 72],
       [84, 35, 70],
       [71, 93, 97]])

In [6]:
b = a.copy()
b

array([[49, 92, 72],
       [84, 35, 70],
       [71, 93, 97]])

In [7]:
b.sort()
b

array([[49, 72, 92],
       [35, 70, 84],
       [71, 93, 97]])

In [8]:
c = a.copy()
c

array([[49, 92, 72],
       [84, 35, 70],
       [71, 93, 97]])

In [9]:
c.sort(axis=0)
c

array([[49, 35, 70],
       [71, 92, 72],
       [84, 93, 97]])

In [10]:
d = a.copy()
d

array([[49, 92, 72],
       [84, 35, 70],
       [71, 93, 97]])

In [11]:
d.sort(axis=1)
d

array([[49, 72, 92],
       [35, 70, 84],
       [71, 93, 97]])

In [12]:
e = np.arange(25).reshape(5, 5)
e

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [13]:
e[0]

array([0, 1, 2, 3, 4])

In [14]:
e[0][0]

np.int64(0)

In [15]:
# famcy indexing
e[0, 0]

np.int64(0)

In [16]:
e[1:][1:]
# e[행:열][행:열]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [17]:
e[1:, 1:]

array([[ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19],
       [21, 22, 23, 24]])

In [18]:
e[1:-1, 1: -1]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [19]:
# 행의 0열과 1열을 가져오라
e[np.array([0, 1])]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
# e[[행], [열]]
# e[[0,0],[1,1]]
e[np.array([0, 1]), np.array([0, 1])]

array([0, 6])

In [21]:
# e [[0,0],[1,1],[2,2]]
e[(0,1,2), (0,1,2)]

array([ 0,  6, 12])

In [22]:
# 짝수만 행렬을 만들어라
e[e%2 ==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [23]:
# 안에 있는 조건이 참인 것만 가져오라
e[e < 5]

array([0, 1, 2, 3, 4])

In [24]:
# 논리값으로 가져오라
e < 5

array([[ True,  True,  True,  True,  True],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])