In [2]:
%pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [3]:
import tensorflow as tf

In [4]:
tf.__version__

'2.20.0'

In [5]:
import numpy as np

from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD
from tensorflow.keras.losses import mse

In [6]:
# 분류문제입니다.
# xor
x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

In [7]:
# layer 를 순차적으로 연결
model = Sequential()

In [8]:
# input layer
model.add(Dense(12, input_shape=(2, ), activation="relu"))

# hidden layer
# input_shape을 지정하지 않으면, 자동으로 이전 layer의 output을 잡아준다.
model.add(Dense(24, activation="relu"))

# ouput layer
model.add(Dense(1, activation="sigmoid"))

/Users/handaeseong/dev/data-engineer/miniconda3/envs/multi02_tensor/lib/python3.9/site-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [9]:
# SGD : Stochastic Gradient Descent (확률적 경사하강법)
# metrics : evaluate (평가) 시 추가할 항목 -> 추가하지 않으면 loss값 만 나온다!
model.compile(loss=mse, optimizer=SGD(), metrics=["acc"])

In [10]:
# epochs : 학습횟수
model.fit(x, y, epochs=1000)

Epoch 1/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 195ms/step - acc: 0.7500 - loss: 0.2537
Epoch 2/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.5000 - loss: 0.2536
Epoch 3/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.7500 - loss: 0.2535
Epoch 4/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.7500 - loss: 0.2534
Epoch 5/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.7500 - loss: 0.2532
Epoch 6/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.7500 - loss: 0.2531
Epoch 7/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - acc: 0.7500 - loss: 0.2530
Epoch 8/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.7500 - loss: 0.2529
Epoch 9/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - acc: 0.7500 - loss: 0.2528
Epoch 10/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - acc: 0.7500 - loss: 0.2527
Epoch 11/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.7500 - loss: 0.2526
Epoch 12/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - acc: 0.7500 - loss: 0.2525
Epoch 13/1000
1/1 ━━━━━━━━━━━━━━━━━━

In [11]:
# evaluate : 평가 -> loss [acc]

model.evaluate(x, y)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - acc: 1.0000 - loss: 0.1663


[0.16630497574806213, 1.0]

In [ ]:
# 분류해줘 잘 예측하고 있네
predict = model.predict(x)
predict

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step


array([[0.44710624],
       [0.6975871 ],
       [0.55725396],
       [0.42170873]], dtype=float32)

In [13]:
# 너가 계산한 값보여줘
# 첫번째에는 W1(weight) W2 가 두번째에는 b(바이어스)
model.get_weights()

[array([[ 0.48072267,  0.26119968,  0.01187084, -0.7356114 , -0.539052  ,
          0.43225846,  0.23195995, -0.0712845 , -0.08110374, -0.5629997 ,
         -0.6044545 ,  0.466942  ],
        [ 0.51298416,  0.17277056,  0.18667129,  0.7357092 ,  0.16129532,
          0.37088653,  0.05373525,  0.19442526, -0.44920236,  0.40613648,
          0.1728331 , -0.42992443]], dtype=float32),
 array([-7.32280090e-02,  1.53129012e-03,  3.14477794e-02,  2.30919861e-04,
         2.44685598e-02,  8.86935013e-05, -5.34322634e-02,  4.99781035e-02,
         0.00000000e+00, -2.28669345e-02,  1.21086976e-02, -1.17174226e-04],
       dtype=float32),
 array([[-2.20649123e-01,  1.85036227e-01,  3.17763388e-01,
          1.77232292e-03,  5.52837774e-02,  3.89278859e-01,
         -5.85442968e-02, -9.94451642e-02,  2.41247594e-01,
         -3.81003350e-01, -3.80227715e-01,  2.80706286e-01,
         -2.49055475e-01, -3.37005347e-01, -3.10400486e-01,
          1.25076532e-01,  2.08412305e-01,  2.49601691e-03,
   