In [4]:
import numpy as np

In [ ]:
# sigmoid
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [ ]:
# sigmoid 미분 (역전파에 사용)
def sigmoid_derivative(x):
    return x * (1 - x)

In [17]:
x = [[0, 0],
      [0, 1],
      [1, 0],
      [1, 1]]
y = [[0],
      [1],
      [1],
      [0]]

x = np.array(x)
y = np.array(y)

In [18]:
# input layer 
input_size = 2
# hidden layer의 perceptron 개수
hidden_size = 4
# output layer
output_size = 1

learning_rate = 0.1
epochs = 10000

In [19]:
np.random.seed(1)

In [20]:
# ipnut -> hidden
weights_input_hidden = np.random.uniform(size=(input_size, hidden_size))
bias_hidden = np.zeros((1, hidden_size))


In [21]:
# hidden -> output
weights_hidden_output = np.random.uniform(size=(hidden_size, output_size))
bias_output = np.zeros((1, output_size))

In [22]:
print(weights_input_hidden)
print(bias_hidden)

print(weights_input_hidden)
print(bias_output)

[[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01]
 [1.46755891e-01 9.23385948e-02 1.86260211e-01 3.45560727e-01]]
[[0. 0. 0. 0.]]
[[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01]
 [1.46755891e-01 9.23385948e-02 1.86260211e-01 3.45560727e-01]]
[[0.]]


In [ ]:
for epoch in range(epochs):
    
    # 1. Forward Propagation (순전파)
    
    # input -> hidden
    hidden_layer_input = np.dot(x, weights_input_hidden) + bias_hidden
    hidden_layer_output = sigmoid(hidden_layer_input)
    
    # hidden -> output
    output_layer_input = np.dot(hidden_layer_output, weights_hidden_output) + bias_output
    predict = sigmoid(output_layer_input)
    
    # 2. loss
    error = y - predict
    
    if epoch % 1000 == 0:
        loss = np.mean(np.square(error)) / 2 
        print(f"[{epoch:04d}] loss : {loss:.6f}")
    
    # 3. Backpropagation (역전파 : 다시 역행하여 w,b 계산을 다시 해줘)
    # error : 손실값
    # output layer 에서 미분    
    d_predict = error * sigmoid_derivative(predict)
    
    # hidden layer -> output layer 의 W, b 다시 계산
    d_weights_hidden_output = np.dot(hidden_layer_output.T, d_predict)
    d_bias_output = np.sum(d_predict, axis=0, keepdims=True)
    
    # hidden layer 에서 미분
    error_hidden_layer = np.dot(d_predict, weights_hidden_output.T)
    d_hidden_layer = error_hidden_layer * sigmoid_derivative(hidden_layer_output)

    # input layer -> hidden layer 의 W, b 다시 계산    
    d_weights_input_hidden = np.dot(x.T, d_hidden_layer)
    d_bias_hidden = np.sum(d_hidden_layer, axis=0, keepdims=True)
    
    # 4. optimizer (gradient descent)
    weights_hidden_output += d_weights_hidden_output * learning_rate
    bias_output += d_bias_output * learning_rate

    weights_input_hidden += d_weights_input_hidden * learning_rate
    bias_hidden += d_bias_hidden * learning_rate


[0000] loss : 0.159033
[1000] loss : 0.124969
[2000] loss : 0.124878
[3000] loss : 0.124530
[4000] loss : 0.122020
[5000] loss : 0.105410
[6000] loss : 0.069767
[7000] loss : 0.021484
[8000] loss : 0.007994
[9000] loss : 0.004401


In [25]:
# 순전파 다시 (최종)
hidden_layer_input = np.dot(x, weights_input_hidden) + bias_hidden
hidden_layer_output = sigmoid(hidden_layer_input)
output_layer_input = np.dot(hidden_layer_output, weights_hidden_output) + bias_output
final_output = sigmoid(output_layer_input)

print(np.round(final_output, 3))

[[0.079]
 [0.925]
 [0.927]
 [0.08 ]]
